### ISSUE TITLE
please improve readme.md

### ISSUE THREAD

**Issue by Usul1980** [saroz014/Plant-Diseases-Recognition#1]
Hi Saroj,

This is a great project, how do we execute it? from terminal?

Thank you in advance!

**Comment by jiawenbin2013** [comment]
This is a great project, how do we execute it? from terminal?

**Comment by Alfinjohnson** [comment]
his is a great project, how do we execute it?

**Comment by saroz014** [comment]
The readme has been updated. Please take a look at it.
