### ISSUE TITLE
Regarding Dataset of plant diseases

### ISSUE THREAD

**Issue by mady143** [saroz014/Plant-Diseases-Recognition#7]
Hi @saroz014 ,
It is very helful for me i want the dataset of plant diseases which you explained in the readme.md file is their any link to download the dataset for that plant diseases 

Thank and Regards,
Manikantha Sekhar.

**Comment by mady143** [comment]
Hi @saroz014 ,
I had found possible data sets in this link https://github.com/lzoran/plant-disease-dataset
Thanks & Regards,
Manikantha Sekhar

**Comment by nawin23** [comment]
@saroz014 brother where i need to paste this dataset https://github.com/lzoran/plant-disease-dataset in the project directory?
